---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: false
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: false
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.slim"
  - "**.scss"
  - "**.js"
  - "**.jsx"
exclude_paths:
- config/
- db/
- spec/
- vendor/
- public/
- log/
- app/assets/images/
